export const White: string = '#FFFFFF'
export const Grey: string = '#3A4144'
export const GreyWhite: string = '#F6F6F6'
export const BorderGrey: string = '#F0F0F0'
export const Red: string = '#D81A3C'
export const Background: string ='#FBFBFB'